#!/bin/bash

pwd
ls
ls -aF

mkdir "test_dir"
cd test_dir
touch test.txt
cp test.txt test2.txt
mv test2.txt ~/PycharmProjects/stolyarov_programming_introduction_to_profession/1_initial/1_2_how_to/1_2_5_directories_files
cd ..
rm -r test_dir
rm test2.txt
